"""cliff_format - official Python implementation for CLIFF 1.0 and 1.1."""

from .converter import (
    XLIFF_VERSIONS,
    from_android_strings,
    from_csv,
    from_dict,
    from_fluent,
    from_ios_strings,
    from_json,
    from_plain_json,
    from_plain_yaml,
    from_po,
    from_xliff,
    from_yaml,
    to_android_strings,
    to_csv,
    to_dict,
    to_fluent,
    to_ios_strings,
    to_json,
    to_po,
    to_xliff,
    to_yaml,
)
from .errors import CliffError, CliffParseError, UnsupportedSpecVersion
from .identifiers import (
    Correction,
    is_name,
    is_style_identifier,
    is_tag,
    normalize_identifier,
    strip_line_terminator,
    unique_identifier,
)
from .model import CliffDocument, Entry, Group, Header, ValidationIssue
from .parser import CANONICAL_VERSION, load, parse, parse_tolerant
from .serializer import serialize
from .validator import (
    ADVISORY_CATEGORIES,
    effective_context,
    effective_emotion,
    effective_max_width,
    effective_type,
    validate,
    validate_document,
)
from .vocabulary import EMOTION_TAGS, GLOSSARY_TYPES, STATUS_TAGS, TYPE_TAGS

__version__ = "0.2.0"

__all__ = [
    "ADVISORY_CATEGORIES",
    "CANONICAL_VERSION",
    "CliffDocument",
    "CliffError",
    "CliffParseError",
    "Correction",
    "EMOTION_TAGS",
    "Entry",
    "GLOSSARY_TYPES",
    "Group",
    "Header",
    "STATUS_TAGS",
    "TYPE_TAGS",
    "UnsupportedSpecVersion",
    "ValidationIssue",
    "XLIFF_VERSIONS",
    "effective_context",
    "effective_emotion",
    "effective_max_width",
    "effective_type",
    "from_android_strings",
    "from_csv",
    "from_dict",
    "from_fluent",
    "from_ios_strings",
    "from_json",
    "from_plain_json",
    "from_plain_yaml",
    "from_po",
    "from_xliff",
    "from_yaml",
    "is_name",
    "is_style_identifier",
    "is_tag",
    "load",
    "normalize_identifier",
    "parse",
    "parse_tolerant",
    "serialize",
    "strip_line_terminator",
    "to_android_strings",
    "to_csv",
    "to_dict",
    "to_fluent",
    "to_ios_strings",
    "to_json",
    "to_po",
    "to_xliff",
    "to_yaml",
    "unique_identifier",
    "validate",
    "validate_document",
    "__version__",
]
