"""cliff_format - official Python implementation for CLIFF 1.0."""

from .converter import (
    XLIFF_VERSIONS,
    from_android_strings,
    from_csv,
    from_dict,
    from_fluent,
    from_ios_strings,
    from_json,
    from_plain_json,
    from_plain_yaml,
    from_po,
    from_xliff,
    from_yaml,
    to_android_strings,
    to_csv,
    to_dict,
    to_fluent,
    to_ios_strings,
    to_json,
    to_po,
    to_xliff,
    to_yaml,
)
from .errors import CliffError, CliffParseError
from .model import CliffDocument, Entry, Group, Header, ValidationIssue
from .parser import load, parse
from .serializer import serialize
from .validator import (
    effective_context,
    effective_emotion,
    effective_max_width,
    effective_type,
    validate,
    validate_document,
)

__version__ = "0.1.0"

__all__ = [
    "XLIFF_VERSIONS",
    "CliffDocument",
    "CliffError",
    "CliffParseError",
    "Entry",
    "Group",
    "Header",
    "ValidationIssue",
    "effective_context",
    "effective_emotion",
    "effective_max_width",
    "effective_type",
    "from_android_strings",
    "from_csv",
    "from_dict",
    "from_fluent",
    "from_ios_strings",
    "from_json",
    "from_plain_json",
    "from_plain_yaml",
    "from_po",
    "from_xliff",
    "from_yaml",
    "load",
    "parse",
    "serialize",
    "to_android_strings",
    "to_csv",
    "to_dict",
    "to_fluent",
    "to_ios_strings",
    "to_json",
    "to_po",
    "to_xliff",
    "to_yaml",
    "validate",
    "validate_document",
    "__version__",
]
